import test from 'node:test';import assert from 'node:assert/strict';import {rank,implied,buildParlay} from '../src/analytics/model.js';import {slateService} from '../src/analytics/slates.js';import {analyticsStore} from '../src/analytics/store.js';import {nextDeadline,submitPick,frozenTicket} from '../src/analytics/league.js';import {openStore} from '../src/store.js';
const q=(id,event,name='Home',price=-110)=>({id,event,book:'hardrockbet_fl',market:'h2h',description:'',point:null,name,price,game:'Away at Home',starts:new Date(Date.now()+86400000).toISOString(),updated:new Date().toISOString()});
test('market ranking separates implied, normalized market probability and unavailable model edge',()=>{assert.equal(implied(100),.5);assert.equal(implied(-300),.75);assert.throws(()=>implied(0));const rows=rank([q('1','a'),q('2','a','Away')],'nfl');assert.equal(rows[0].score,50);assert.equal(rows[0].edge,null);assert.equal(rows[0].modelProbability,null);assert.equal(rank([q('1','a')],'nfl')[0].marketProbability,null);});
test('parlays reject insufficient independent games and never price correlated combinations',()=>{const rows=rank([q('1','a'),q('2','a','Away'),q('3','b'),q('4','b','Away')],'nfl');const ticket=buildParlay(rows,2);assert.equal(ticket.legs.length,2);assert.equal(new Set(ticket.legs.map(q=>q.event)).size,2);assert.throws(()=>buildParlay(rows,3),/Only 2/);});
test('prop pool fetches each eligible event and reports partial provider failure',async()=>{const events=['a','b','c'].map(id=>({id,commence_time:new Date(Date.now()+3600000).toISOString(),home_team:'Home',away_team:'Away'}));let calls=[];const svc=slateService({events:async()=>events,odds:async(_s,e,m)=>{calls.push([e,m]);if(e==='b')throw Error('down');return [q(e+'1',e),q(e+'2',e,'Away')];}},{capture:()=>{}});const result=await svc('nfl','touchdowns');assert.equal(calls.length,3);assert.equal(result.covered,2);assert.deepEqual(result.failures,['b']);assert.ok(calls.every(c=>c[1]==='player_anytime_td'));});
test('deadline uses Wednesday 6PM ET including winter offset',()=>{assert.equal(nextDeadline(new Date('2026-09-08T12:00:00Z')),'2026-09-09T22:00:00.000Z');assert.equal(nextDeadline(new Date('2026-12-01T12:00:00Z')),'2026-12-02T23:00:00.000Z');});
test('league submissions replace before lock and frozen tickets remain immutable',()=>{const s=openStore(':memory:'),h=analyticsStore(s),db=h.db;db.prepare('INSERT INTO league_groups(group_key) VALUES(?)').run('A');db.prepare('INSERT INTO league_members VALUES(?,?)').run('user','A');db.prepare('INSERT INTO weeks(id,deadline) VALUES(?,?)').run('w',new Date(Date.now()+3600000).toISOString());s.set('analytics:week','w');submitPick(s,db,'user',q('1','a'),'nfl');submitPick(s,db,'user',q('2','b'),'nfl');assert.equal(db.prepare('SELECT COUNT(*) n FROM league_picks').get().n,1);db.prepare('UPDATE weeks SET locked=1').run();assert.throws(()=>submitPick(s,db,'user',q('3','c'),'nfl'),/locked/);const ticket=frozenTicket(s,db,'A');assert.equal(JSON.parse(ticket.snapshot)[0].id,'2');assert.equal(frozenTicket(s,db,'A').snapshot,ticket.snapshot);s.db.close();});
import {mixedPool} from '../src/analytics/mixed-props.js';
import '../src/analytics/discord.js';
test('mixed categories preserve coverage and exclude no-touchdown selections',async()=>{const result=await mixedPool(async(_s,c)=>({rows:rank([q(c+'1',c,c==='touchdowns'?'Yes':'Over'),q(c+'2',c,c==='touchdowns'?'No':'Under')],'nfl'),games:1,covered:1,failures:[]}), 'nfl',['passing','touchdowns','passing']);assert.deepEqual(result.categories,['passing','touchdowns']);assert.equal(result.rows.length,3);assert.equal(result.coverage.length,2);assert.ok(result.rows.filter(x=>x.category==='touchdowns').every(x=>x.name==='Yes'));await assert.rejects(()=>mixedPool(()=>{},'nfl',['hits']),/supported/);});
test('mixed ticket backtracks to include all categories across distinct games',()=>{const rows=rank([q('1','a'),q('2','b'),q('3','a')],'nfl').map(x=>({...x,category:x.id==='3'?'rushing':'passing'}));const ticket=buildParlay(rows,2,false,['passing','rushing']);assert.deepEqual(new Set(ticket.legs.map(x=>x.category)),new Set(['passing','rushing']));assert.equal(new Set(ticket.legs.map(x=>x.event)).size,2);assert.throws(()=>buildParlay(rows,2,false,['receiving']),/No eligible current selections/);});

test('slates route moneylines and prop categories to each selected sportsbook',async()=>{for(const book of ['hardrockbet_fl','fanduel','draftkings']){const calls=[];const svc=slateService({events:async()=>[{id:'a',commence_time:new Date(Date.now()+3600000).toISOString()}],odds:async(s,e,m,b)=>{calls.push(b);return [{...q('1','a'),book:b}];}},{capture:()=>{}});assert.equal((await svc('nfl','moneyline',{book})).rows[0].book,book);const mixed=await mixedPool(svc,'nfl',['passing','receiving'],{book});assert.ok(mixed.rows.every(x=>x.book===book));assert.deepEqual(calls,[book,book,book]);await assert.rejects(()=>svc('nfl','moneyline',{book:'invalid'}),/supported sportsbook/);}});
test('explicit same-game mode fits multiple categories without fabricating parlay price',()=>{const rows=rank(['passing','rushing','receiving','touchdowns'].map((category,n)=>({...q(String(n),'one'),market:category,description:'Player '+n,category})),'nfl');assert.throws(()=>buildParlay(rows,4,false,rows.map(r=>r.category)),/same_game:true/);const t=buildParlay(rows,4,true,rows.map(r=>r.category));assert.equal(t.legs.length,4);assert.equal(t.estimatedAmericanOdds,null);assert.equal(t.combinedProbability,null);assert.match(t.warning,/correlated/);assert.throws(()=>buildParlay(rows,4,true,['missing']),/No eligible current selections/);});
