import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {adapter,gameMatches,applyEdits,resolveTicket} from '../src/screenshots/normalize.js';import {imageMime,downloadImage,recognize} from '../src/screenshots/vision.js';import {screenshotStore} from '../src/screenshots/store.js';import {openStore} from '../src/store.js';import {installScreenshots,screenshotCommands,sourceAllowed} from '../src/screenshots/discord.js';import {commands} from '../src/commands.js';
const leg={player:'A.J. Brown',market:'receiving_yards',direction:'at_least',line:64,alternate_line:true,confidence:1,game:'NE vs SEA'};
const ticket={legs:[leg],leg_count:1,warnings:[],sportsbook:null,sport:'NFL',odds:4500,wager:5,potential_payout:230,cash_out:5,bet_type:'SGP',game_time_text:'Today 8:20 PM'};
const date=new Date(Date.now()+86400000).toISOString().slice(0,10);
const quote={id:'q',event:'e',game:'New England Patriots at Seattle Seahawks',description:'AJ Brown',name:'Over',market:'player_reception_yds_alternate',point:63.5,book:'hardrockbet_fl',price:-110,starts:new Date(Date.now()+86400000).toISOString(),updated:new Date().toISOString()};
const api={events:async()=>[{id:'e',away_team:'New England Patriots',home_team:'Seattle Seahawks',commence_time:quote.starts}],odds:async()=>[quote]};
test('screenshot normalization preserves threshold semantics, sport matchup and user corrections',()=>{assert.equal(adapter(leg).point,63.5);assert.equal(adapter({...leg,direction:'over'}).point,64);assert.ok(gameMatches('NE SEA Today 8:20 PM',{away_team:'New England Patriots',home_team:'Seattle Seahawks'},'nfl'));assert.ok(!gameMatches('NE vs SEA',{away_team:'Philadelphia Eagles',home_team:'Indianapolis Colts'},'nfl'));assert.equal(applyEdits({ticket},'AJ Brown | receiving_yards | at_least | 64 | NE vs SEA').ticket.legs[0].line,64);assert.throws(()=>applyEdits({ticket},'broken'));});
test('image resolver requires real date and exact current outcomes; normalizes punctuation',async()=>{const d={ticket,sport:'nfl',book:'hardrockbet_fl',from:date};assert.equal((await resolveTicket(api,d)).quotes[0].id,'q');await assert.rejects(()=>resolveTicket(api,{...d,from:null}),/actual game date/);await assert.rejects(()=>resolveTicket(api,{...d,ticket:{...ticket,legs:[{...leg,line:65}]}}),/no exact/);await assert.rejects(()=>resolveTicket({...api,odds:async()=>[{...quote,starts:'2020-01-01'}]},d),/no exact/);});
test('attachment safety rejects external URLs and malformed image types',async()=>{assert.throws(()=>imageMime(Buffer.from('html')));await assert.rejects(()=>downloadImage({url:'https://evil.example/x.png',size:1}),/Discord image/);await assert.rejects(()=>downloadImage({url:'https://cdn.discordapp.com.evil.example/attachments/x',size:1}));await assert.rejects(()=>downloadImage({url:'https://cdn.discordapp.com/attachments/x',size:9000000}));});
test('raw reads stay immutable, edits separate, owner and revision checks protect records',()=>{const s=openStore(':memory:'),r=screenshotStore(s),id=r.create('u','c','m',{url:'image'});r.read(id,ticket);r.read(id,{...ticket,odds:5000});r.update(id,{draft_json:JSON.stringify(ticket)});assert.equal(JSON.parse(r.get(id,'u').raw_json).odds,4500);assert.throws(()=>r.get(id,'other'));assert.throws(()=>r.get(id,'u',0));r.update(id,{status:'cancelled'});assert.throws(()=>r.get(id,'u'));s.db.close();});
test('registered image command is valid and automatic detection skips winnings/feed channels',()=>{assert.ok(commands.find(c=>c.name==='analyze-image'));assert.equal(screenshotCommands[0].options[0].type,11);assert.equal(sourceAllowed({isTextBased:()=>true,name:'winning-tickets'}, {get:()=>null}),false);});
test('Discord screenshot workflow requires confirmation, edits, exact matches and explicit posting',async()=>{const handlers={},s=openStore(':memory:');s.set('memberRole','member');s.set('adminRole','admin');s.set('channels:nfl',{chat:'dest'});let analyses=0,posts=0;const allowed={has:()=>true};const dest={id:'dest',name:'nfl-bet-discussion',isTextBased:()=>true,permissionsFor:()=>allowed,send:async()=>{posts++;}};const guild={channels:{fetch:async()=>{},cache:new Map([['dest',dest]])},members:{fetchMe:async()=>({}),fetch:async()=>({})}};const client={on:(event,fn)=>handlers[event]=fn};const r=installScreenshots(client,s,{...api,analyze:async()=>{analyses++;return 'Cited research report';}},{DISCORD_GUILD_ID:'g'},{download:async()=>({bytes:Buffer.alloc(1),mime:'image/png'}),read:async()=>ticket});
function interaction(action,owner='u'){return {guildId:'g',guild,user:{id:owner},channelId:'source',member:{roles:{cache:new Map([['member',{}]])}},commandName:action==='start'?'analyze-image':undefined,customId:action==='start'?undefined:action,isChatInputCommand:()=>action==='start',isButton:()=>action!=='start'&&!action.endsWith(':save'),isModalSubmit:()=>action.endsWith(':save'),options:{getAttachment:()=>({url:'image',size:1,name:'slip.png'}),getString:k=>k==='sport'?'nfl':k==='from'?date:null},deferReply:async function(){this.deferred=true;},editReply:async function(v){this.output=v;},reply:async function(v){this.output=v;},showModal:async function(v){this.modal=v;}};}
const start=interaction('start');await handlers.interactionCreate(start);assert.equal(analyses,0);let rec=s.db.prepare('SELECT * FROM screenshot_slips').get();assert.ok(start.output.embeds.length);const forbidden=interaction(`ss:${rec.id}:${rec.revision}:match`,'other');await handlers.interactionCreate(forbidden);assert.equal(analyses,0);const edit=interaction(`ss:${rec.id}:${rec.revision}:edit`);await handlers.interactionCreate(edit);assert.ok(edit.modal);const saved=interaction(`ss:${rec.id}:${rec.revision}:save`);saved.fields={getTextInputValue:k=>({sport:'nfl',book:'hardrockbet_fl',date,legs:'AJ Brown | receiving_yards | at_least | 64 | NE vs SEA',amounts:'4500 | 5 | 230 | 5'})[k]};await handlers.interactionCreate(saved);rec=r.get(rec.id,'u');assert.equal(JSON.parse(rec.draft_json).ticket.legs[0].player,'AJ Brown');assert.equal(JSON.parse(rec.raw_json).legs[0].player,'A.J. Brown');const match=interaction(`ss:${rec.id}:${rec.revision}:match`);await handlers.interactionCreate(match);assert.equal(analyses,0);assert.ok(match.output.embeds[0].data.description.includes('Destination: <#dest>'));rec=r.get(rec.id,'u');const post=interaction(`ss:${rec.id}:${rec.revision}:post`);await handlers.interactionCreate(post);assert.equal(analyses,1);assert.equal(posts,1);await handlers.interactionCreate(post);assert.equal(posts,1);assert.ok(s.db.prepare('SELECT confirmed_json,result_json FROM screenshot_slips').get().result_json);s.db.close();});
test('automatic upload detection reads privately before any analysis and supports cancel',async()=>{const handlers={},s=openStore(':memory:');s.set('memberRole','member');let reads=0,analysis=0;const client={on:(e,f)=>handlers[e]=f};installScreenshots(client,s,{analyze:async()=>analysis++},{DISCORD_GUILD_ID:'g',SCREENSHOT_AUTO_DETECT:'true'},{download:async()=>({bytes:Buffer.alloc(1),mime:'image/png'}),read:async()=>{reads++;return ticket;}});let response;const message={guildId:'g',id:'message',channelId:'source',author:{id:'u',bot:false},member:{roles:{cache:new Map([['member',{}]])}},channel:{id:'source',name:'general-chat',isTextBased:()=>true},attachments:new Map([['a',{url:'image',size:1,name:'slip.png'}]]),reply:async v=>response=v};message.attachments.find=fn=>[...message.attachments.values()].find(fn);await handlers.messageCreate(message);assert.equal(reads,1);assert.equal(analysis,0);assert.ok(!response.content.includes('Brown'));const rec=s.db.prepare('SELECT * FROM screenshot_slips').get();const i={guildId:'g',user:{id:'u'},member:message.member,customId:`ss:${rec.id}:${rec.revision}:cancel`,isChatInputCommand:()=>false,isButton:()=>true,isModalSubmit:()=>false,deferReply:async()=>{},editReply:async()=>{}};await handlers.interactionCreate(i);assert.equal(s.db.prepare('SELECT status FROM screenshot_slips').get().status,'cancelled');s.db.close();});
