import {SlashCommandBuilder as C,ActionRowBuilder as Row,ButtonBuilder as Button,ButtonStyle as B,MessageFlags as F,EmbedBuilder as Embed,ModalBuilder,TextInputBuilder,TextInputStyle,PermissionFlagsBits as P} from 'discord.js';
import {SPORTS,BOOKS,BOOK,quoteLine,clean} from '../core.js';
import {splitMessages} from '../research.js';
import {PublicError} from '../errors.js';
import {downloadImage,recognize} from './vision.js';
import {screenshotStore} from './store.js';
import {resolveTicket,editLines,applyEdits} from './normalize.js';
const footer='Statistical research only. No outcome is guaranteed. No wagers or payments are handled.';
export const screenshotCommands=[new C().setName('analyze-image').setDescription('Read a bet-slip image, edit and confirm it, then research').setDMPermission(false).addAttachmentOption(o=>o.setName('image').setDescription('PNG, JPEG or WebP, maximum 8 MB').setRequired(true)).addStringOption(o=>o.setName('sport').setDescription('Override recognized sport').addChoices(...Object.entries(SPORTS).map(([value,s])=>({name:s.name,value})))).addStringOption(o=>o.setName('book').setDescription('Confirm sportsbook; default Hard Rock Florida').addChoices(...Object.entries(BOOKS).map(([value,name])=>({value,name})))).addStringOption(o=>o.setName('from').setDescription('Actual game date YYYY-MM-DD UTC; do not use image Today label')).toJSON()];
const row=(...components)=>new Row().addComponents(...components);
const txt=(id,label,value,max=100)=>new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(id==='legs'?TextInputStyle.Paragraph:TextInputStyle.Short).setRequired(true).setMaxLength(max).setValue(String(value||'').slice(0,max));
export function sourceAllowed(channel,store){return channel?.isTextBased()&&(['general-chat','parlay-picks','group-parlay-upload','general-discussion'].includes(channel.name)||Object.keys(SPORTS).some(s=>channel.id&&store.get('channels:'+s)?.chat===channel.id)||/^(nfl|nba|nhl|mlb|cfb|cbb)-bet-discussion$/.test(channel.name));}
export function installScreenshots(client,store,api,env,{read=recognize,download=downloadImage}={}){
 const records=screenshotStore(store),busy=new Set(),cooldown=new Map();
 const member=m=>m?.roles?.cache?.has(store.get('memberRole'))||m?.roles?.cache?.has(store.get('adminRole'));
 function log(id,status,start){console.log(JSON.stringify({event:'screenshot',id,status,ms:Date.now()-start}));}
 function buttons(s,mode='draft'){const items=mode==='matched'?[['post','Analyze and post to sport chat',B.Success],['edit','Edit Legs',B.Secondary],['cancel','Cancel',B.Danger]]:[['match','Analyze',B.Success],['edit','Edit Legs',B.Secondary],['reread','Re-Read Image',B.Secondary],['cancel','Cancel',B.Danger]];return [row(...items.map(([a,l,style])=>new Button().setCustomId(`ss:${s.id}:${s.revision}:${a}`).setLabel(l).setStyle(style)))];}
 async function preview(i,id,extra=''){const s=records.get(id,i.user.id),d=JSON.parse(s.draft_json),t=d.ticket;const lines=t.legs.map((l,n)=>`${n+1}. ${clean(l.player||'Unknown',80)} | ${clean(l.market,45)} | ${clean(l.direction,20)} ${l.line??''}\nGame: ${clean(l.game||'Not shown',100)}${l.confidence<.85?' | LOW RECOGNITION CONFIDENCE - edit required':''}`);
 const desc=`Sport: ${SPORTS[d.sport]?.name||'Unknown - edit required'} | Selected book: ${BOOKS[d.book]}\nImage book: ${clean(t.sportsbook||'Not identified')} | Type: ${clean(t.bet_type||'Unknown')}\nDate: ${d.from||'Not confirmed - set with Edit Legs'} | Image time: ${clean(t.game_time_text||'Not shown')}\nImage odds: ${t.odds??'Unknown'} | Wager: ${t.wager??'Unknown'} | Payout: ${t.potential_payout??'Unknown'} | Cash out: ${t.cash_out??'Not shown'}\n\n${lines.join('\n')}\n\n${clean((t.warnings||[]).join('; '),400)}\n${t.leg_count!==null&&t.leg_count!==t.legs.length?'Leg count mismatch: edit or re-read before continuing.':''}\nRecognition confidence measures reading quality, not betting probability. Review every field. Analysis will first validate current odds. ${extra}`;
 await i.editReply({content:'',embeds:[new Embed().setTitle('Bet slip detected - review required').setColor(0x14765b).setDescription(desc.slice(0,4000)).setFooter({text:footer})],components:buttons(s),allowedMentions:{parse:[]}});}
 async function extract(id,owner,overrides={}){const s=records.get(id,owner);const {bytes,mime}=await download(JSON.parse(s.attachment_json));const raw=await read(bytes,mime,env,store);records.read(id,raw);const prior=s.draft_json?JSON.parse(s.draft_json):{};const sport=overrides.sport||prior.sport||String(raw.sport||raw.league||'').toLowerCase();const draft={ticket:{...raw,legs:raw.legs.map(l=>({...l,market:l.market?.trim().toLowerCase().replace(/\s+/g,'_')||null}))},sport,book:overrides.book||prior.book||BOOK,from:overrides.from||prior.from||null,reviewed:false};records.update(id,{draft_json:JSON.stringify(draft),quotes_json:null,status:'draft'});}
 async function destination(i,d){if(!SPORTS[d.sport])throw new PublicError('Set a supported sport with Edit Legs.');await i.guild.channels.fetch();const id=store.get('channels:'+d.sport)?.chat;const channel=i.guild.channels.cache.get(id)||i.guild.channels.cache.find(c=>c.name===d.sport+'-bet-discussion');if(!channel||!channel.isTextBased())throw new PublicError('No discussion channel is configured for this sport. Ask a commissioner to configure it.');const me=await i.guild.members.fetchMe();const user=await i.guild.members.fetch(i.user.id);if(!channel.permissionsFor(user)?.has([P.ViewChannel,P.SendMessages])||!channel.permissionsFor(me)?.has([P.ViewChannel,P.SendMessages,P.EmbedLinks]))throw new PublicError('You and the bot need access to the destination sport chat.');return channel;}
 client.on('messageCreate',async m=>{if(env.SCREENSHOT_AUTO_DETECT!=='true'||m.guildId!==env.DISCORD_GUILD_ID||m.author.bot||!member(m.member)||!sourceAllowed(m.channel,store))return;const a=m.attachments.find(a=>/\.(png|jpe?g|webp)$/i.test(a.name||''));if(!a||busy.has(m.author.id)||(cooldown.get(m.author.id)||0)>Date.now())return;busy.add(m.author.id);cooldown.set(m.author.id,Date.now()+15000);let id,start=Date.now();try{id=records.create(m.author.id,m.channelId,m.id,{url:a.url,size:a.size,name:a.name});await extract(id,m.author.id);const s=records.get(id,m.author.id);await m.reply({content:'Bet-slip image read. Open your private review to correct the sport, date and picks before analysis.',components:[row(new Button().setCustomId(`ss:${id}:${s.revision}:open`).setLabel('Review my slip').setStyle(B.Primary))],allowedMentions:{parse:[],repliedUser:false}});log(id,'recognized',start);}catch(e){if(id)records.update(id,{status:'error'});await m.reply({content:e instanceof PublicError?e.message:'Screenshot reading failed. Try /analyze-image with a clearer image.',allowedMentions:{parse:[],repliedUser:false}}).catch(()=>{});log(id,'failed',start);}finally{busy.delete(m.author.id);}});
 client.on('interactionCreate',async i=>{
  const start=i.isChatInputCommand()&&i.commandName==='analyze-image',component=(i.isButton()||i.isModalSubmit())&&i.customId.startsWith('ss:');if(!start&&!component)return;if(i.guildId!==env.DISCORD_GUILD_ID)return;
  if(!member(i.member))return i.reply({content:'Member role required.',flags:F.Ephemeral});
  if(busy.has(i.user.id))return i.reply({content:'Your previous screenshot step is still running.',flags:F.Ephemeral});
  busy.add(i.user.id);const began=Date.now();let id;
  try{
   if(start){if((cooldown.get(i.user.id)||0)>Date.now())throw new PublicError('Wait a few seconds before another screenshot.');cooldown.set(i.user.id,Date.now()+15000);await i.deferReply({flags:F.Ephemeral});const a=i.options.getAttachment('image');id=records.create(i.user.id,i.channelId,null,{url:a.url,size:a.size,name:a.name});await extract(id,i.user.id,{sport:i.options.getString('sport'),book:i.options.getString('book'),from:i.options.getString('from')});await preview(i,id);log(id,'recognized',began);return;}
   const [,sid,rev,action]=i.customId.split(':');id=sid;const s=records.get(id,i.user.id,Number(rev)),d=JSON.parse(s.draft_json);
   if(action==='edit'){const modal=new ModalBuilder().setCustomId(`ss:${id}:${s.revision}:save`).setTitle('Correct recognized ticket').addComponents(row(txt('sport','Sport: nfl, nba, mlb, nhl, cfb, cbb',d.sport,10)),row(txt('book','Book: hardrockbet_fl, fanduel, draftkings',d.book,20)),row(txt('date','Actual game date: YYYY-MM-DD (UTC)',d.from,10)),row(txt('legs','name | market | direction | line | game',editLines(d.ticket),3500)),row(txt('amounts','Image odds | wager | payout | cash out',[d.ticket.odds,d.ticket.wager,d.ticket.potential_payout,d.ticket.cash_out].map(v=>v??'').join(' | '),120)));await i.showModal(modal);return;}
   await i.deferReply({flags:F.Ephemeral});
   if(action==='open'){await preview(i,id);return;}
   if(action==='cancel'){records.update(id,{status:'cancelled'});await i.editReply('Cancelled. No analysis or publication performed.');return;}
   if(action==='save'){const draft=applyEdits(d,i.fields.getTextInputValue('legs'));draft.sport=i.fields.getTextInputValue('sport').trim().toLowerCase();draft.book=i.fields.getTextInputValue('book').trim().toLowerCase();draft.from=i.fields.getTextInputValue('date').trim();const vals=i.fields.getTextInputValue('amounts').split('|').map(v=>v.trim()===''?null:Number(v.trim()));if(vals.length!==4||vals.some(v=>v!==null&&!Number.isFinite(v))||vals.slice(1).some(v=>v!==null&&v<0)||vals[0]!==null&&(!Number.isInteger(vals[0])||Math.abs(vals[0])<100))throw new PublicError('Use American odds and nonnegative amounts, separated by |. Leave unknown fields blank.');[draft.ticket.odds,draft.ticket.wager,draft.ticket.potential_payout,draft.ticket.cash_out]=vals;if(!SPORTS[draft.sport]||!BOOKS[draft.book])throw new PublicError('Use one of the listed sport and book keys.');if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.from)||!Number.isFinite(Date.parse(draft.from)))throw new PublicError('Use a valid YYYY-MM-DD date.');records.update(id,{draft_json:JSON.stringify(draft),quotes_json:null,status:'draft'});await preview(i,id);return;}
   if(action==='reread'){await extract(id,i.user.id);await preview(i,id);return;}
   if(action==='match'){
    if(d.ticket.legs.some(l=>l.confidence<.85)||d.ticket.leg_count!==null&&d.ticket.leg_count!==d.ticket.legs.length)throw new PublicError('Use Edit Legs to correct and verify low-confidence or missing selections first.');
    const target=await destination(i,d);const resolved=await resolveTicket(api,d);records.update(id,{confirmed_json:JSON.stringify(d),quotes_json:JSON.stringify(resolved),status:'matched'});const current=records.get(id,i.user.id);await i.editReply({embeds:[new Embed().setTitle('Verify current sportsbook matches').setDescription((resolved.quotes.map(quoteLine).join('\n\n')+'\n\nDestination: <#'+target.id+'>. Clicking the button researches and POSTS the report there. The screenshot and wager amounts are not reposted. Current odds may differ from the image. Model probability, fair odds and EV are unavailable.').slice(0,4000)).setFooter({text:footer})],components:buttons(current,'matched'),allowedMentions:{parse:[]}});return;
   }
   if(action==='post'){
    if(s.status!=='matched'||!s.confirmed_json)throw new PublicError('Confirm the recognized selections first.');const confirmed=JSON.parse(s.confirmed_json),target=await destination(i,confirmed),matched=JSON.parse(s.quotes_json);
    // Existing analysis refreshes every quote and rejects expired, started or duplicate selections.
    const report=await api.analyze(confirmed.sport,matched.quotes.map(q=>q.id));const result={report,created_at:new Date().toISOString(),probability:null,fair_odds:null,ev:null,model:'research-only',matched_odds_updated:matched.quotes.map(q=>q.updated)};
    records.update(id,{result_json:JSON.stringify(result),status:'publishing'});let posted=0;
    try{for(const part of splitMessages(report)){await target.send({embeds:[new Embed().setTitle('Parlay screenshot research').setDescription(part).setColor(0x14765b).setFooter({text:footer})],allowedMentions:{parse:[]}});posted++;}}catch{records.update(id,{status:'complete'});throw new PublicError('Research saved, but publication was interrupted. '+posted+' report sections were posted; ask the commissioner to retrieve the saved report.');}
    records.update(id,{status:'complete'});await i.editReply('Analysis posted in <#'+target.id+'>. Screenshot record: '+id);log(id,'complete',began);return;
   }
  }catch(e){log(id,'failed',began);const msg=e instanceof PublicError?e.message:'Screenshot step failed. Check provider access and try again; no missing data was invented.';if(i.deferred||i.replied)await i.editReply({content:msg,embeds:[],components:[]}).catch(()=>{});else await i.reply({content:msg,flags:F.Ephemeral}).catch(()=>{});}finally{busy.delete(i.user.id);}
 });
 return records;
}
