import {SlashCommandBuilder as C} from 'discord.js';
const sport=o=>o.setName('sport').setDescription('Sport').setRequired(true).addChoices(...['nfl','nba','mlb','nhl','cfb','cbb'].map(value=>({name:value.toUpperCase(),value})));
const book=o=>o.setName('book').setDescription('Sportsbook; default Hard Rock Bet Florida').addChoices({name:'Hard Rock Bet Florida',value:'hardrockbet_fl'},{name:'FanDuel',value:'fanduel'},{name:'DraftKings',value:'draftkings'});
const date=o=>o.setName('from').setDescription('7-day slate starts YYYY-MM-DD UTC; default today');
const group=o=>o.setName('group').setDescription('League group').setRequired(true).addChoices({name:'Group A',value:'A'},{name:'Group B',value:'B'});
const c=(n,d)=>new C().setName(n).setDescription(d).setDMPermission(false);
const ranked=(n,d)=>c(n,d).addStringOption(sport).addStringOption(n==='prop-parlay'?o=>o.setName('from').setDescription('Only this date in Eastern time: YYYY-MM-DD or today; default today'):date).addStringOption(book);
export const analyticsCommands=[c('analyze-slip','Paste picks, review exact sportsbook matches, then analyze').addStringOption(sport).addStringOption(o=>o.setName('picks').setDescription('Comma-separated picks, e.g. Kupp over 2.5 receps, JSN ATTD').setRequired(true).setMaxLength(1500)).addStringOption(book).addStringOption(date),c('flea','Open the analytics center'),ranked('moneyline','Available slate moneylines and transparent price rankings'),
 c('ml','Sport-specific moneyline slate').addSubcommand(s=>s.setName('nfl').setDescription('NFL').addStringOption(date).addStringOption(book)).addSubcommand(s=>s.setName('nba').setDescription('NBA').addStringOption(date).addStringOption(book)).addSubcommand(s=>s.setName('mlb').setDescription('MLB').addStringOption(date).addStringOption(book)).addSubcommand(s=>s.setName('nhl').setDescription('NHL').addStringOption(date).addStringOption(book)),
 ranked('props','Cross-game player prop pool').addStringOption(o=>o.setName('category').setDescription('NFL/college football market group').addChoices(...['passing','rushing','receiving','touchdowns'].map(value=>({name:value,value})))).addStringOption(o=>o.setName('player').setDescription('Filter player name')).addStringOption(o=>o.setName('game').setDescription('Filter team name')),
 c('td','NFL touchdown analysis and recorded season history')
 .addSubcommand(s=>s.setName('slate').setDescription('All available anytime TD markets in a 7-day NFL slate').addStringOption(date).addStringOption(book).addStringOption(o=>o.setName('filter').setDescription('Market-price filter; value estimates unavailable').addChoices({name:'Most likely (market)',value:'likely'},{name:'Plus money',value:'plus'},{name:'Longshots (+300 or longer)',value:'longshot'})))
 .addSubcommand(s=>s.setName('player').setDescription('Recorded official TD history').addStringOption(o=>o.setName('name').setDescription('Exact player name').setRequired(true)).addIntegerOption(o=>o.setName('season').setDescription('Season').setRequired(true)))
 .addSubcommand(s=>s.setName('leaderboard').setDescription('Recorded season touchdown leaderboard').addIntegerOption(o=>o.setName('season').setDescription('Season').setRequired(true)).addStringOption(o=>o.setName('sort').setDescription('Sort field').addChoices(...['total_tds','td_game_rate','red_zone_touches'].map(value=>({name:value,value}))))),
 ranked('parlay','Build a market-ranked moneyline ticket; not a value model').addIntegerOption(o=>o.setName('legs').setDescription('3-4 conservative; 5-6 balanced; 7-9 aggressive; 12 FLEA. No ticket is safe.').setMinValue(2).setMaxValue(12)),
 ranked('prop-parlay','Choose multiple prop categories and optionally allow same-game legs').addBooleanOption(o=>o.setName('same_game').setDescription('Allow multiple legs from one game; sportsbook pricing required')).addIntegerOption(o=>o.setName('legs').setDescription('Number of legs: 4, 6, 8, or 12').addChoices(...[4,6,8,12].map(value=>({name:String(value),value})))),
 c('bestbets','Current professional-sport market board; value model pending'),
 c('history','Your recorded analysis selections'),c('model','Recorded baseline performance and calibration status'),
 c('results','Officially graded research selections; hypothetical unit ROI').addStringOption(o=>o.setName('period').setDescription('Time window').addChoices(...['today','week','season'].map(value=>({name:value,value})))),
 c('disclaimer','Informational-only use and independent betting decisions'),
 c('pick','Privately submit a current analyzed quote to your group').addStringOption(sport).addStringOption(o=>o.setName('quote').setDescription('Quote ID').setRequired(true)),
 c('admin','Commissioner-only analytics and league controls')
 .addSubcommand(s=>s.setName('refresh-odds').setDescription('Clear odds cache for next retrieval'))
 .addSubcommand(s=>s.setName('rebuild-analysis').setDescription('Clear analysis cache'))
 .addSubcommand(s=>s.setName('set-week').setDescription('Create/select a week and deadline').addStringOption(o=>o.setName('week').setDescription('Week identifier').setRequired(true)).addStringOption(o=>o.setName('deadline').setDescription('ISO timestamp with timezone; default next Wednesday 6 PM ET')).addStringOption(o=>o.setName('market').setDescription('Allowed pick type').addChoices(...['any','h2h','props','td'].map(value=>({name:value,value})))))
 .addSubcommand(s=>s.setName('assign').setDescription('Assign Group A/B; maximum 12 members each').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(group))
 .addSubcommand(s=>s.setName('group-channel').setDescription('Set existing group ticket destination').addStringOption(group).addChannelOption(o=>o.setName('channel').setDescription('Private group text channel').setRequired(true)))
 .addSubcommand(s=>s.setName('lock-picks').setDescription('Lock current week'))
 .addSubcommand(s=>s.setName('unlock-picks').setDescription('Unlock before deadline; extend deadline first if expired'))
 .addSubcommand(s=>s.setName('publish-ticket').setDescription('Publish frozen group submissions after lock').addStringOption(group))
 .addSubcommand(s=>s.setName('grade').setDescription('Record verified official result; no auto inference').addIntegerOption(o=>o.setName('id').setDescription('Analysis record ID').setRequired(true)).addStringOption(o=>o.setName('outcome').setDescription('Official settlement').setRequired(true).addChoices(...['win','loss','push','void'].map(value=>({name:value,value})))).addStringOption(o=>o.setName('source').setDescription('Official HTTPS result URL').setRequired(true)))
].map(x=>x.toJSON());
