import {exactDay} from './dates.js';
import {matchSlip} from './slip.js';
import {shareMessages} from './share.js';
import {PROP_CATEGORIES,mixedPool} from './mixed-props.js';
import {PermissionFlagsBits as P,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,MessageFlags as F} from 'discord.js';
import {randomUUID} from 'node:crypto';
import {analyticsCommands} from './commands.js';import {analyticsStore} from './store.js';import {slateService} from './slates.js';import {buildParlay,decimal} from './model.js';import {currentWeek,nextDeadline,submitPick,frozenTicket} from './league.js';
import {quoteLine,assertFresh} from '../core.js';import {splitMessages} from '../research.js';
export const DISCLAIMER='Discussion and statistical research only. No wagers, funds, or payouts are handled. Prices change; each member independently decides whether to use their own authorized sportsbook account.';
export function installAnalytics(client,store,api,env){
 const history=analyticsStore(store),db=history.db,slate=slateService(api,history),sessions=new Map(),busy=new Set(),last=new Map();
 const names=new Set(analyticsCommands.map(x=>x.name));
 const row=x=>new ActionRowBuilder().addComponents(x);
 async function reply(i,text,components=[]){const chunks=splitMessages(text);await i.editReply({content:chunks[0],components:chunks.length===1?components:[],allowedMentions:{parse:[]}});for(let n=1;n<chunks.length;n++)await i.followUp({content:chunks[n],components:n===chunks.length-1?components:[],flags:F.Ephemeral,allowedMentions:{parse:[]}});}
 async function share(i,ticket){for(const content of shareMessages(ticket.legs))await i.followUp({content,flags:F.Ephemeral,allowedMentions:{parse:[]}});}
 async function board(i,result,title){
  const sid=randomUUID();sessions.set(sid,{owner:i.user.id,...result,title,page:0,expires:Date.now()+1800000});await page(i,sid);
 }
 async function page(i,sid){const s=sessions.get(sid);const rows=s.rows.slice(s.page*5,s.page*5+5);const text=`**${s.title}**\n${s.games} scheduled games; ${s.covered} with returned markets; ${s.failures.length} failed event requests. Seven-day UTC window from ${s.from}.\n**Market baseline only. Model probability, projections, edge and value ratings unavailable.**\n`+rows.map((q,n)=>`\n${s.page*5+n+1}. ${quoteLine(q)}\nImplied ${(q.impliedProbability*100).toFixed(1)}% | FLEA market score ${q.score??'N/A'}/100 (not a win prediction)\n${q.reason}\nMissing: ${q.missingFactors.join(', ')}\nUpdated ${q.updated} | Quote ${q.id}`).join('\n')+(rows.length?'':'\nNo eligible current markets returned. No substitute sportsbook or invented picks.')+'\n\n'+DISCLAIMER;
 const components=[];if(rows.length)components.push(row(new StringSelectMenuBuilder().setCustomId('fa:'+sid+':analyze').setPlaceholder('Research one selection before submitting').addOptions(rows.map((q,n)=>({label:`${q.description||q.name} ${q.point??''} ${q.price}`.slice(0,100),value:String(s.page*5+n)})))));
 const buttons=new ActionRowBuilder();if(s.page>0)buttons.addComponents(new ButtonBuilder().setCustomId('fa:'+sid+':prev').setLabel('Previous').setStyle(ButtonStyle.Secondary));if((s.page+1)*5<s.rows.length)buttons.addComponents(new ButtonBuilder().setCustomId('fa:'+sid+':next').setLabel('Next').setStyle(ButtonStyle.Secondary));if(buttons.components.length)components.push(buttons);await reply(i,text,components);
 }
 client.on('interactionCreate',async i=>{
  const command=i.isChatInputCommand()&&names.has(i.commandName);const component=(i.isButton()||i.isStringSelectMenu())&&i.customId.startsWith('fa:');if(!command&&!component)return;if(i.guildId!==env.DISCORD_GUILD_ID)return;
  const roles=i.member?.roles;const has=id=>Array.isArray(roles)?roles.includes(id):roles?.cache?.has(id);const admin=has(store.get('adminRole'));
  if(!admin&&!has(store.get('memberRole')))return i.reply({content:'Member role required.',flags:F.Ephemeral});if(i.commandName==='admin'&&!admin)return i.reply({content:'Commissioner role required.',flags:F.Ephemeral});
  if(busy.has(i.user.id)||(last.get(i.user.id)||0)>Date.now())return i.reply({content:'Please wait before the next request.',flags:F.Ephemeral});busy.add(i.user.id);last.set(i.user.id,Date.now()+2000);
  try{await i.deferReply({flags:F.Ephemeral});
   if(component){const [,sid,action]=i.customId.split(':');
    if(sid==='menu'){const [sport,category]=i.values[0].split('|');await board(i,{...await slate(sport,category),sport},`${sport.toUpperCase()} ${category}`);return;}
    const s=sessions.get(sid);if(!s||s.owner!==i.user.id||s.expires<Date.now())throw Error('Menu expired. Run the command again.');
    if(action==='confirm-slip'){if(s.used)throw Error('This slip was already analyzed. Run /analyze-slip again.');s.used=true;await reply(i,await api.analyze(s.sport,s.legs.map(q=>q.id)));return;}
    if(action==='categories'){
     if(s.used)throw Error('This builder was already used. Run /prop-parlay again.');
     const result=await mixedPool(slate,s.sport,i.values,s.filter);
     const ticket=buildParlay(result.rows,s.legs,s.allowSameGame,result.categories);
     db.prepare('INSERT INTO parlays(owner,created_at,style,snapshot) VALUES(?,?,?,?)').run(i.user.id,new Date().toISOString(),'mixed-props',JSON.stringify({...ticket,categories:result.categories,coverage:result.coverage}));s.used=true;
     await reply(i,'**Multi-category prop parlay**\nGame date: '+s.filter.from+' (Eastern time only)\nCategories: '+result.categories.map(c=>PROP_CATEGORIES[s.sport][c]).join(', ')+'\nEvery selected category is represented.\n'+ticket.legs.map(q=>'['+PROP_CATEGORIES[s.sport][q.category]+'] '+quoteLine(q)).join('\n')+'\nEstimated Parlay Odds: '+(ticket.estimatedAmericanOdds??'Unavailable for correlated legs')+'\n'+ticket.warning+'\n\nCoverage: '+result.coverage.map(c=>c.category+': '+c.covered+'/'+c.games+' games, '+c.failures+' failed requests').join('; ')+'\nMarket-price ranking, not a calibrated value model. Research these legs using /analyze sport:'+s.sport+' quotes:'+ticket.legs.map(q=>q.id).join(',')+'\n'+DISCLAIMER);await share(i,ticket);return;
    }
    if(action==='next'||action==='prev'){s.page=Math.max(0,Math.min(Math.ceil(s.rows.length/5)-1,s.page+(action==='next'?1:-1)));await page(i,sid);return;}
    const q=s.rows[Number(i.values[0])];if(!q)throw Error('Invalid selection');const text=await api.analyze(s.sport,[q.id]);const refreshed=(await api.odds(s.sport,q.event,q.market,q.book)).find(x=>x.id===q.id);if(!refreshed)throw Error('Line no longer available.');const record=history.save(i.user.id,s.sport,{...q,...refreshed});await reply(i,text+`\nAnalysis record: ${record}. Submit privately with /pick sport:${s.sport} quote:${q.id}`);return;
   }
   const o=i.options,n=i.commandName;const sport=o.getString('sport')||(['ml'].includes(n)?o.getSubcommand(): 'nfl');const filter={book:o.getString('book')||undefined,from:o.getString('from')||undefined,player:o.getString('player')||undefined,game:o.getString('game')||undefined};
   if(n==='analyze-slip'){
    const matched=await matchSlip(slate,o.getString('picks'),sport,filter);
    if(!matched.ready){await reply(i,'**Review needed - no analysis run**\n'+matched.results.map((r,n)=>(n+1)+'. '+(r.candidates.length===1?quoteLine(r.candidates[0]):r.candidates.length?'Ambiguous match. Use the full name and a narrower date window: '+r.candidates.slice(0,3).map(quoteLine).join(' | '):'No exact available match. Check the player spelling, market and line.')).join('\n')+'\nCorrect the corresponding pick in your original list and rerun /analyze-slip. Typos and different lines are not substituted.\nCoverage: '+matched.coverage.join('; '));return;}
    const sid=randomUUID();sessions.set(sid,{owner:i.user.id,sport,legs:matched.legs,expires:Date.now()+1800000});await reply(i,'**Confirm your pasted slip**\n'+matched.legs.map(quoteLine).join('\n')+'\nVerify full player names, games, outcomes, lines and sportsbook. Confirmation researches these selections; it places no wager.\nCoverage: '+matched.coverage.join('; '),[row(new ButtonBuilder().setCustomId('fa:'+sid+':confirm-slip').setLabel('Confirm and analyze').setStyle(ButtonStyle.Primary))]);return;
   }
   if(n==='prop-parlay'){
    filter.exactDate=true;filter.from=exactDay(filter.from);

    const choices=PROP_CATEGORIES[sport];if(!choices)throw Error('Unsupported sport.');const sid=randomUUID();sessions.set(sid,{owner:i.user.id,sport,filter,allowSameGame:o.getBoolean('same_game')??(env.ALLOW_CORRELATED_PROPS==='true'),legs:o.getInteger('legs')||4,expires:Date.now()+1800000});
    await reply(i,'**Build a multi-category prop parlay**\nGame date: '+filter.from+' (Eastern time only). Started games are excluded.\nSelect one or more categories in this menu, then submit your selection. The ticket will include at least one leg from each selected category. '+(sessions.get(sid).allowSameGame?'Same-game legs are enabled. These can be correlated; check the final combination and price in your sportsbook.':'Different games are required. To allow several picks from one matchup, rerun with same_game:true.')+' If a category is unavailable, the bot will explain rather than substitute it.',[row(new StringSelectMenuBuilder().setCustomId('fa:'+sid+':categories').setPlaceholder('Choose your prop categories').setMinValues(1).setMaxValues(Object.keys(choices).length).addOptions(Object.entries(choices).map(([value,label])=>({label,value}))))]);return;
   }
   if(n==='flea'){const entries=[];for(const s of ['nfl','nba','mlb','nhl'])for(const category of ['moneyline',...(s==='nfl'?['passing','rushing','receiving','touchdowns']:[s])])entries.push({label:`${s.toUpperCase()} - ${category==='moneyline'?'Moneyline Analyzer':category==='touchdowns'?'Anytime TD Hunter':'Prop Lab: '+category}`,value:s+'|'+category});await reply(i,'**F.L.E.A ANALYTICS CENTER**\nChoose a research board.\nParlays: /parlay, /prop-parlay\nDaily board: /bestbets\nHistory: /history, /results, /model\nLeague: /pick\n'+DISCLAIMER,[row(new StringSelectMenuBuilder().setCustomId('fa:menu:open').addOptions(entries))]);
   }else if(['moneyline','ml','props','parlay','prop-parlay'].includes(n)||n==='td'&&o.getSubcommand()==='slate'){
    const category=n==='td'?'touchdowns':['props','prop-parlay'].includes(n)?o.getString('category')||(['nfl','cfb'].includes(sport)?'receiving':sport):'moneyline';const actualSport=n==='td'?'nfl':sport;const result=await slate(actualSport,category,filter);
    if(category==='touchdowns')result.rows=result.rows.filter(q=>q.name.toLowerCase()==='yes');
    if(n==='td'){const f=o.getString('filter');result.rows=result.rows.filter(q=>q.name.toLowerCase()==='yes'&&(!f||f==='likely'||f==='plus'&&q.price>0||f==='longshot'&&q.price>=300));}
    if(['parlay','prop-parlay'].includes(n)){const ticket=buildParlay(result.rows,o.getInteger('legs')||4,env.ALLOW_CORRELATED_PROPS==='true');db.prepare('INSERT INTO parlays(owner,created_at,style,snapshot) VALUES(?,?,?,?)').run(i.user.id,new Date().toISOString(),n,JSON.stringify(ticket));await reply(i,`**Suggested price-band-diversified ticket - not value-optimized**\n`+ticket.legs.map(quoteLine).join('\n')+`\nEstimated Parlay Odds: ${ticket.estimatedAmericanOdds??'Unavailable for correlated legs'}\n${ticket.warning}\nResearch each leg using /analyze sport:${actualSport} quotes:${ticket.legs.map(q=>q.id).join(',')}\n`+DISCLAIMER);await share(i,ticket);}
    else await board(i,{...result,sport:actualSport},n==='td'?'NFL ANYTIME TD HUNTER':`${actualSport.toUpperCase()} ${category}`);
   }else if(n==='td'){const season=o.getInteger('season');if(o.getSubcommand()==='player'){const rows=db.prepare('SELECT * FROM player_td_stats WHERE player_name=? COLLATE NOCASE AND season=?').all(o.getString('name'),season);await reply(i,rows.length?rows.map(p=>`**${p.player_name} (${p.team}) ${season}**\nGames ${p.games_played??'N/A'} | TDs ${p.total_tds??'N/A'} | Games with TD ${p.games_with_td??'N/A'}\nRush ${p.rush_tds??'N/A'} | Receiving ${p.receiving_tds??'N/A'}\nLast five: `+db.prepare('SELECT tds FROM player_td_games WHERE player_id=? AND season=? ORDER BY game_date DESC LIMIT 5').all(p.player_id,season).map(g=>g.tds>0?'TD':'No TD').join(', ')+`\n${p.source_url} | Updated ${p.last_updated}`).join('\n'):'No verified player TD history imported. A structured historical source is not configured.');}else{const sort=o.getString('sort')||'total_tds';if(!['total_tds','td_game_rate','red_zone_touches'].includes(sort))throw Error('Invalid sort');const rows=db.prepare(`SELECT * FROM player_td_stats WHERE season=? ORDER BY ${sort} DESC LIMIT 15`).all(season);await reply(i,rows.length?rows.map(p=>`${p.player_name}: ${p[sort]??'N/A'} | ${p.source_url}`).join('\n'):'No verified season history imported. No fabricated leaderboard.');}
   }else if(n==='history'){await reply(i,history.history(i.user.id).map(a=>`#${a.id} ${a.created_at} ${quoteLine(JSON.parse(a.snapshot))} | ${a.outcome||'Ungraded'}`).join('\n')||'No recorded selections. Use a board selection to run research.');
   }else if(n==='results'||n==='model'){const period=n==='model'?'season':o.getString('period')||'week';const now=new Date();const since=period==='today'?now.toISOString().slice(0,10):period==='week'?new Date(+now-7*86400000).toISOString():`${now.getUTCFullYear()}-01-01`;const rs=history.results(since);const wl=rs.filter(x=>['win','loss'].includes(x.outcome));const wins=wl.filter(x=>x.outcome==='win').length;const net=wl.reduce((sum,x)=>sum+(x.outcome==='win'?decimal(JSON.parse(x.snapshot).price)-1:-1),0);await reply(i,`**Recorded model scorecard**\nMarket baseline only; uncalibrated. Season window = calendar year.\nWins ${wins} | Losses ${wl.length-wins} | Push/void ${rs.length-wl.length}\nHit rate ${wl.length?(100*wins/wl.length).toFixed(1)+'%':'N/A'}\nHypothetical 1-unit ROI ${wl.length?(100*net/wl.length).toFixed(1)+'%':'N/A'} (wins/losses only; no money handled).\nOnly commissioner-verified results are counted. No grades means no performance claim.`);
   }else if(n==='bestbets'){const text=[];for(const s of ['nfl','nba','mlb','nhl']){try{const data=await slate(s);if(data.games)text.push(`${s.toUpperCase()}: ${data.rows[0]?quoteLine(data.rows[0]):'Hard Rock unavailable'}\nMarket rank only. Use /props for prop pool${s==='nfl'?' and /td slate for touchdowns':''}.`);}catch{text.push(`${s.toUpperCase()}: provider unavailable`);}}await reply(i,'**DAILY MARKET BOARD - not verified best value**\n'+text.join('\n\n'));
   }else if(n==='pick'){const q=store.cached(`quote:${sport}:${o.getString('quote')}`);if(!q)throw Error('Quote expired. Refresh the board.');const fresh=(await api.odds(sport,q.event,q.market,q.book)).find(x=>x.id===q.id);if(!fresh)throw Error('Selection no longer offered.');await reply(i,submitPick(store,db,i.user.id,fresh,sport));
   }else if(n==='disclaimer')await reply(i,DISCLAIMER);
   else if(n==='admin')await adminAction(i);
  }catch(e){await reply(i,['PublicError','Error'].includes(e.constructor.name)&&!e.code?String(e.message).slice(0,400):'Request failed. Check provider access or configuration; no results were invented.').catch(()=>{});}
  finally{busy.delete(i.user.id);for(const[k,s]of sessions)if(s.expires<Date.now())sessions.delete(k);}
 });
 async function adminAction(i){const o=i.options,action=o.getSubcommand();
  if(action==='refresh-odds')db.prepare("DELETE FROM cache WHERE key LIKE 'odds:%' OR key LIKE 'events:%'").run();
  else if(action==='rebuild-analysis')db.prepare("DELETE FROM cache WHERE key LIKE 'ai-research:%'").run();
  else if(action==='set-week'){const deadline=o.getString('deadline')||nextDeadline();if(!/T.*(Z|[+-]\d\d:\d\d)$/.test(deadline)||!(Date.parse(deadline)>Date.now()))throw Error('Use a future ISO deadline with timezone offset.');db.prepare('INSERT INTO weeks(id,deadline,allowed_market) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET deadline=excluded.deadline,allowed_market=excluded.allowed_market').run(o.getString('week'),new Date(deadline).toISOString(),o.getString('market')||'any');store.set('analytics:week',o.getString('week'));}
  else if(action==='assign'){const group=o.getString('group'),user=o.getUser('member');if(user.bot)throw Error('Choose a human member');const count=db.prepare('SELECT COUNT(*) AS n FROM league_members WHERE group_key=? AND user_id<>?').get(group,user.id).n;if(count>=12)throw Error('Group already has 12 members');db.prepare('INSERT OR IGNORE INTO league_groups(group_key) VALUES(?)').run(group);const roleName='Group '+group;await i.guild.roles.fetch();let role=i.guild.roles.cache.find(r=>r.name===roleName);if(!role)role=await i.guild.roles.create({name:roleName});const member=await i.guild.members.fetch(user.id);await member.roles.add(role);for(const other of ['Group A','Group B'])if(other!==roleName){const r=i.guild.roles.cache.find(r=>r.name===other);if(r&&member.roles.cache.has(r.id))await member.roles.remove(r);}db.prepare('UPDATE league_groups SET role_id=? WHERE group_key=?').run(role.id,group);db.prepare('INSERT INTO league_members VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET group_key=excluded.group_key').run(user.id,group);}
  else if(action==='group-channel'){const c=o.getChannel('channel');if(c.type!==0||c.guildId!==i.guildId)throw Error('Choose a text channel in this server.');db.prepare('INSERT INTO league_groups(group_key,channel_id) VALUES(?,?) ON CONFLICT(group_key) DO UPDATE SET channel_id=excluded.channel_id').run(o.getString('group'),c.id);}
  else if(action==='lock-picks'||action==='unlock-picks'){const w=currentWeek(store,db);if(action==='unlock-picks'&&Date.parse(w.deadline)<=Date.now())throw Error('Extend the deadline before unlocking.');db.prepare('UPDATE weeks SET locked=? WHERE id=?').run(action==='lock-picks'?1:0,w.id);}
  else if(action==='publish-ticket'){const group=o.getString('group'),ticket=frozenTicket(store,db,group);if(ticket.message_id)throw Error('Ticket already published.');const config=db.prepare('SELECT * FROM league_groups WHERE group_key=?').get(group);if(!config?.channel_id)throw Error('Configure group-channel first.');const channel=await client.channels.fetch(config.channel_id);if(channel.permissionsFor(i.guild.roles.everyone)?.has(P.ViewChannel))throw Error('Group destination must be private.');const text=`**GROUP ${group} CONSENSUS TICKET - ${ticket.week_id}**\nMember submissions, deduplicated; not a statistically optimized consensus. Prices are submission snapshots, not current quotes.\n`+JSON.parse(ticket.snapshot).map(quoteLine).join('\n')+'\n'+DISCLAIMER;let message;for(const content of splitMessages(text))message=await channel.send({content,allowedMentions:{parse:[]}});db.prepare('UPDATE consensus_tickets SET message_id=?,published_at=? WHERE week_id=? AND group_key=?').run(message.id,new Date().toISOString(),ticket.week_id,group);}
  else if(action==='grade'){const record=db.prepare('SELECT * FROM analysis_results WHERE id=?').get(o.getInteger('id'));if(!record)throw Error('Unknown analysis ID');if(Date.parse(JSON.parse(record.snapshot).starts)>Date.now())throw Error('Game has not started; cannot grade.');const url=new URL(o.getString('source'));if(url.protocol!=='https:'||!['nfl.com','nba.com','mlb.com','nhl.com','espn.com','sports.yahoo.com'].some(d=>url.hostname===d||url.hostname.endsWith('.'+d)))throw Error('Provide the official HTTPS result source.');db.prepare('INSERT INTO results(analysis_id,outcome,source_url,graded_by,graded_at) VALUES(?,?,?,?,?)').run(record.id,o.getString('outcome'),url.href,i.user.id,new Date().toISOString());}
  store.audit(i.user.id,'analytics:'+action);await reply(i,'Commissioner action completed.');
 }
 const timer=setInterval(()=>{try{currentWeek(store,db);}catch{}},30000);timer.unref();
 return names;
}

