import {readFileSync} from 'node:fs';import {openStore} from '../store.js';import {analyticsStore} from './store.js';
// Local commissioner-operated import; one full verified season snapshot per player.
export function importTD(db,rows){if(!Array.isArray(rows)||rows.length>10000)throw Error('Expected an array of at most 10000 player records');
 const prepared=rows.map(r=>{const url=new URL(r.source_url);if(url.protocol!=='https:'||!['nfl.com','espn.com','sports.yahoo.com','sportsdata.io'].some(d=>url.hostname===d||url.hostname.endsWith('.'+d)))throw Error('Use a supported official/statistics source URL');
 if(!r.player_id||!r.player_name||!r.team||!Number.isInteger(r.season)||!Array.isArray(r.games))throw Error('Missing player identity, season or games');
 if(new Set(r.games.map(g=>g.event_id)).size!==r.games.length)throw Error('Duplicate game');
 for(const g of r.games){if(!g.event_id||!Number.isFinite(Date.parse(g.game_date))||Date.parse(g.game_date)>Date.now()||![g.rush_tds,g.receiving_tds].every(n=>Number.isInteger(n)&&n>=0))throw Error('Each completed game needs date and nonnegative rush/receiving TD counts');}
 const rush=r.games.reduce((s,g)=>s+g.rush_tds,0),receiving=r.games.reduce((s,g)=>s+g.receiving_tds,0),withTD=r.games.filter(g=>g.rush_tds+g.receiving_tds>0).length;
 return {...r,total_tds:rush+receiving,rush_tds:rush,receiving_tds:receiving,games_played:r.games.length,games_with_td:withTD,td_game_rate:r.games.length?withTD/r.games.length:null};});
 db.exec('BEGIN');try{for(const r of prepared){db.prepare('INSERT INTO player_td_stats(player_id,player_name,team,season,games_played,total_tds,rush_tds,receiving_tds,games_with_td,td_game_rate,last_updated,source_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(player_id,season) DO UPDATE SET player_name=excluded.player_name,team=excluded.team,games_played=excluded.games_played,total_tds=excluded.total_tds,rush_tds=excluded.rush_tds,receiving_tds=excluded.receiving_tds,games_with_td=excluded.games_with_td,td_game_rate=excluded.td_game_rate,last_updated=excluded.last_updated,source_url=excluded.source_url').run(String(r.player_id),r.player_name,r.team,r.season,r.games_played,r.total_tds,r.rush_tds,r.receiving_tds,r.games_with_td,r.td_game_rate,new Date().toISOString(),r.source_url);db.prepare('DELETE FROM player_td_games WHERE player_id=? AND season=?').run(String(r.player_id),r.season);for(const g of r.games)db.prepare('INSERT INTO player_td_games VALUES(?,?,?,?,?,?)').run(String(r.player_id),r.season,g.event_id,g.game_date,g.rush_tds+g.receiving_tds,r.source_url);}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return prepared.length;}
if(process.argv[1]?.replaceAll('\\','/').endsWith('/import-td.js')){const s=openStore(process.env.DATABASE_PATH);try{const h=analyticsStore(s);console.log('Imported player snapshots: '+importTD(h.db,JSON.parse(readFileSync(process.argv[2],'utf8'))));}catch{console.error('Import rejected. Check the documented verified-data schema; no credentials are printed.');process.exitCode=1;}finally{s.db.close();}}
