import {assertFresh} from '../core.js';
export function nextDeadline(now=new Date()){
 const fmt=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'});
 for(let d=0;d<8;d++){const day=fmt.format(new Date(+now+d*86400000));const test=new Date(day+'T12:00:00Z');if(test.getUTCDay()!==3)continue;for(const h of [22,23]){const t=new Date(day+`T${h}:00:00Z`);if(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',hourCycle:'h23'}).format(t)==='18'&&t>now)return t.toISOString();}}
 throw Error('Deadline unavailable');
}
export function currentWeek(store,db){const w=db.prepare('SELECT * FROM weeks WHERE id=?').get(store.get('analytics:week')||'');if(!w)throw Error('Commissioner must configure the week first.');if(Date.parse(w.deadline)<=Date.now()&&!w.locked){db.prepare('UPDATE weeks SET locked=1 WHERE id=?').run(w.id);w.locked=1;}return w;}
export function submitPick(store,db,user,q,sport){assertFresh(q);const w=currentWeek(store,db);if(w.locked)throw Error('Picks are locked.');const member=db.prepare('SELECT * FROM league_members WHERE user_id=?').get(user);if(!member)throw Error('Ask the commissioner to assign Group A or B.');if(w.allowed_market==='h2h'&&q.market!=='h2h'||w.allowed_market==='props'&&!/^(player|batter|pitcher)_/.test(q.market)||w.allowed_market==='td'&&q.market!=='player_anytime_td')throw Error('Selection does not match the assigned weekly market.');db.prepare('INSERT INTO league_picks VALUES(?,?,?,?,?) ON CONFLICT(week_id,user_id) DO UPDATE SET snapshot=excluded.snapshot,submitted_at=excluded.submitted_at').run(w.id,user,member.group_key,JSON.stringify({...q,sport}),new Date().toISOString());return 'Your private pick was saved. Resubmitting replaces it until the deadline.';}
export function frozenTicket(store,db,group){const w=currentWeek(store,db);if(!w.locked)throw Error('Lock picks before publishing.');const old=db.prepare('SELECT * FROM consensus_tickets WHERE week_id=? AND group_key=?').get(w.id,group);if(old)return old;const picks=db.prepare('SELECT snapshot FROM league_picks WHERE week_id=? AND group_key=?').all(w.id,group).map(x=>JSON.parse(x.snapshot));if(!picks.length)throw Error('No submitted picks.');const unique=[...new Map(picks.map(q=>[q.id,q])).values()];db.prepare('INSERT INTO consensus_tickets(week_id,group_key,snapshot) VALUES(?,?,?)').run(w.id,group,JSON.stringify(unique));return db.prepare('SELECT * FROM consensus_tickets WHERE week_id=? AND group_key=?').get(w.id,group);}
